title: KZSH
author:
  name: Kz Sherwin
  email: kzsherdev@gmail.com
description: "" # this means to ignore newlines until "show_excerpts:"
show_excerpts: false # set to true to show excerpts on the homepage
permalink: /posts/:year-:month-:day/:title
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.kzsher.com" # the base hostname & protocol for your site, e.g. http://example.com

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
# Build settings
theme: minima
minima:
  skin: dark
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  kz-sher
    twitter: false
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: kzsher
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Issue: Not able to use the github verison of minima theme
# Solution: https://github.com/jekyll/minima/issues/411#issuecomment-730711365
remote_theme: jekyll/minima

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md